version: '2'
services:
    hockeysubscoreboard-app:
        image: hockeysubscoreboard
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://hockeysubscoreboard-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=HockeySubScoreBoard
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hockeysubscoreboard-mongodb:
        extends:
            file: mongodb.yml
            service: hockeysubscoreboard-mongodb
